# Matrix

In [2]:
vector = [1,2,3,4]

In [5]:
matrix = [
    [1,2,5],
    [3,4,6]
]

In [11]:
print(matrix)

[[1, 2, 5], [3, 4, 6]]


In [32]:
def print_matrix(data_matrix):
    rows = len(data_matrix)
    cols = len(data_matrix[0])
    
    for m in range(rows):
        for n in range(cols): 
            print(f"{data_matrix[m][n]} ",end="")
        print(f"\n",end="")
    

In [33]:
print_matrix(matrix)

1 2 5 
3 4 6 


In [34]:
matrix_1 = [
    [1,2,5],
    [3,4,6]
]

matrix_2 = [
    [1,1,1],
    [1,1,1]
]

In [35]:
def penjumlahan_matrix(data_matrix_1, data_matrix_2):
    rows = len(data_matrix_1)
    cols = len(data_matrix_1[0])
    
    matrix_luar = []
    for m in range(rows):
        vector_dalam = []
        for n in range(cols): 
            hasil = data_matrix_1[m][n] + data_matrix_2[m][n]
            vector_dalam.append(hasil)
        matrix_luar.append(vector_dalam)
    
    return matrix_luar


In [36]:
penjumlahan_matrix(matrix_1, matrix_2)

[[2, 3, 6], [4, 5, 7]]

In [37]:
matrix_1 = [
    [1,2,5,6],
    [3,4,6,9],
    [3,4,6,9],
    [3,4,6,9]
]

matrix_2 = [
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
]

In [40]:
matrix_3 = penjumlahan_matrix(matrix_1, matrix_2)

In [41]:
print_matrix(matrix_3)

2 3 6 7 
4 5 7 10 
4 5 7 10 
4 5 7 10 


In [43]:
import numpy as np

In [46]:
matrix_a = np.array(matrix_1)
matrix_b = np.array(matrix_2)
matrix_c = matrix_a + matrix_b

In [48]:
print(matrix_c)

[[ 2  3  6  7]
 [ 4  5  7 10]
 [ 4  5  7 10]
 [ 4  5  7 10]]
